import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'ServiceHub Tunisia',
      'welcome': 'Welcome',
      'login': 'Login',
      'register': 'Register',
      'phone': 'Phone Number',
      'password': 'Password',
      'email': 'Email',
      'name': 'Full Name',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': 'Don\'t have an account?',
      'already_have_account': 'Already have an account?',
      'home': 'Home',
      'search': 'Search',
      'bookings': 'Bookings',
      'profile': 'Profile',
      'services': 'Services',
      'providers': 'Providers',
      'categories': 'Categories',
      'popular_services': 'Popular Services',
      'maintenance': 'Maintenance',
      'cleaning': 'Cleaning',
      'childcare': 'Childcare',
      'transport': 'Transport',
      'beauty': 'Beauty',
      'plumbing': 'Plumbing',
      'electricity': 'Electricity',
      'ac': 'Air Conditioning',
      'from': 'From',
      'tnd': 'TND',
      'book_now': 'Book Now',
      'view_details': 'View Details',
      'select_service': 'Select Service',
      'select_date': 'Select Date',
      'select_time': 'Select Time',
      'description': 'Description',
      'urgent': 'Urgent',
      'urgent_surcharge': 'Urgent surcharge applied',
      'confirm_booking': 'Confirm Booking',
      'my_addresses': 'My Addresses',
      'add_address': 'Add Address',
      'edit_address': 'Edit Address',
      'delete_address': 'Delete Address',
      'set_as_default': 'Set as Default',
      'address_label': 'Address Label',
      'address_line1': 'Address Line 1',
      'address_line2': 'Address Line 2',
      'city': 'City',
      'postal_code': 'Postal Code',
      'save': 'Save',
      'cancel': 'Cancel',
      'notifications': 'Notifications',
      'mark_all_read': 'Mark All as Read',
      'no_notifications': 'No Notifications',
      'settings': 'Settings',
      'help_support': 'Help & Support',
      'about': 'About',
      'logout': 'Logout',
      'logout_confirmation': 'Are you sure you want to logout?',
      'yes': 'Yes',
      'no': 'No',
      'pending': 'Pending',
      'confirmed': 'Confirmed',
      'in_progress': 'In Progress',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'rating': 'Rating',
      'reviews': 'Reviews',
      'submit_review': 'Submit Review',
      'overall_rating': 'Overall Rating',
      'professionalism': 'Professionalism',
      'quality': 'Quality',
      'value_for_money': 'Value for Money',
      'comment': 'Comment',
      'submit': 'Submit',
      'provider_dashboard': 'Provider Dashboard',
      'statistics': 'Statistics',
      'total_revenue': 'Total Revenue',
      'upcoming_bookings': 'Upcoming Bookings',
      'required_field': 'This field is required',
      'invalid_phone': 'Invalid phone number',
      'invalid_email': 'Invalid email address',
      'password_min_length': 'Password must be at least 8 characters',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'retry': 'Retry',
    },
    'fr': {
      'app_name': 'ServiceHub Tunisie',
      'welcome': 'Bienvenue',
      'login': 'Connexion',
      'register': 'S\'inscrire',
      'phone': 'Numéro de téléphone',
      'password': 'Mot de passe',
      'email': 'Email',
      'name': 'Nom complet',
      'forgot_password': 'Mot de passe oublié?',
      'dont_have_account': 'Vous n\'avez pas de compte?',
      'already_have_account': 'Vous avez déjà un compte?',
      'home': 'Accueil',
      'search': 'Rechercher',
      'bookings': 'Réservations',
      'profile': 'Profil',
      'services': 'Services',
      'providers': 'Prestataires',
      'categories': 'Catégories',
      'popular_services': 'Services populaires',
      'maintenance': 'Maintenance',
      'cleaning': 'Nettoyage',
      'childcare': 'Garde',
      'transport': 'Transport',
      'beauty': 'Beauté',
      'plumbing': 'Plomberie',
      'electricity': 'Électricité',
      'ac': 'Climatisation',
      'from': 'À partir de',
      'tnd': 'TND',
      'book_now': 'Réserver maintenant',
      'view_details': 'Voir les détails',
      'select_service': 'Sélectionner un service',
      'select_date': 'Sélectionner une date',
      'select_time': 'Sélectionner une heure',
      'description': 'Description',
      'urgent': 'Urgent',
      'urgent_surcharge': 'Surcharge urgente appliquée',
      'confirm_booking': 'Confirmer la réservation',
      'my_addresses': 'Mes adresses',
      'add_address': 'Ajouter une adresse',
      'edit_address': 'Modifier l\'adresse',
      'delete_address': 'Supprimer l\'adresse',
      'set_as_default': 'Définir par défaut',
      'address_label': 'Nom de l\'adresse',
      'address_line1': 'Adresse ligne 1',
      'address_line2': 'Adresse ligne 2',
      'city': 'Ville',
      'postal_code': 'Code postal',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'notifications': 'Notifications',
      'mark_all_read': 'Tout marquer comme lu',
      'no_notifications': 'Aucune notification',
      'settings': 'Paramètres',
      'help_support': 'Aide & Support',
      'about': 'À propos',
      'logout': 'Déconnexion',
      'logout_confirmation': 'Êtes-vous sûr de vouloir vous déconnecter?',
      'yes': 'Oui',
      'no': 'Non',
      'pending': 'En attente',
      'confirmed': 'Confirmé',
      'in_progress': 'En cours',
      'completed': 'Terminé',
      'cancelled': 'Annulé',
      'rating': 'Note',
      'reviews': 'Avis',
      'submit_review': 'Soumettre un avis',
      'overall_rating': 'Note globale',
      'professionalism': 'Professionnalisme',
      'quality': 'Qualité',
      'value_for_money': 'Rapport qualité/prix',
      'comment': 'Commentaire',
      'submit': 'Soumettre',
      'provider_dashboard': 'Tableau de bord',
      'statistics': 'Statistiques',
      'total_revenue': 'Revenu total',
      'upcoming_bookings': 'Réservations à venir',
      'required_field': 'Ce champ est obligatoire',
      'invalid_phone': 'Numéro de téléphone invalide',
      'invalid_email': 'Adresse email invalide',
      'password_min_length': 'Le mot de passe doit contenir au moins 8 caractères',
      'loading': 'Chargement...',
      'error': 'Erreur',
      'success': 'Succès',
      'retry': 'Réessayer',
    },
    'ar': {
      'app_name': 'سرفيس هاب تونس',
      'welcome': 'مرحبا',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'phone': 'رقم الهاتف',
      'password': 'كلمة المرور',
      'email': 'البريد الإلكتروني',
      'name': 'الاسم الكامل',
      'forgot_password': 'نسيت كلمة المرور؟',
      'dont_have_account': 'ليس لديك حساب؟',
      'already_have_account': 'لديك حساب بالفعل؟',
      'home': 'الرئيسية',
      'search': 'بحث',
      'bookings': 'الحجوزات',
      'profile': 'الملف الشخصي',
      'services': 'الخدمات',
      'providers': 'مقدمو الخدمات',
      'categories': 'الفئات',
      'popular_services': 'الخدمات الشائعة',
      'maintenance': 'الصيانة',
      'cleaning': 'التنظيف',
      'childcare': 'رعاية الأطفال',
      'transport': 'النقل',
      'beauty': 'الجمال',
      'plumbing': 'السباكة',
      'electricity': 'الكهرباء',
      'ac': 'تكييف الهواء',
      'from': 'من',
      'tnd': 'دينار',
      'book_now': 'احجز الآن',
      'view_details': 'عرض التفاصيل',
      'select_service': 'اختر الخدمة',
      'select_date': 'اختر التاريخ',
      'select_time': 'اختر الوقت',
      'description': 'الوصف',
      'urgent': 'عاجل',
      'urgent_surcharge': 'رسوم عاجلة مطبقة',
      'confirm_booking': 'تأكيد الحجز',
      'my_addresses': 'عناويني',
      'add_address': 'إضافة عنوان',
      'edit_address': 'تعديل العنوان',
      'delete_address': 'حذف العنوان',
      'set_as_default': 'تعيين كافتراضي',
      'address_label': 'اسم العنوان',
      'address_line1': 'العنوان سطر 1',
      'address_line2': 'العنوان سطر 2',
      'city': 'المدينة',
      'postal_code': 'الرمز البريدي',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'notifications': 'الإشعارات',
      'mark_all_read': 'وضع علامة مقروء على الكل',
      'no_notifications': 'لا توجد إشعارات',
      'settings': 'الإعدادات',
      'help_support': 'المساعدة والدعم',
      'about': 'حول',
      'logout': 'تسجيل الخروج',
      'logout_confirmation': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'yes': 'نعم',
      'no': 'لا',
      'pending': 'قيد الانتظار',
      'confirmed': 'مؤكد',
      'in_progress': 'جارٍ',
      'completed': 'مكتمل',
      'cancelled': 'ملغى',
      'rating': 'التقييم',
      'reviews': 'المراجعات',
      'submit_review': 'إرسال مراجعة',
      'overall_rating': 'التقييم الإجمالي',
      'professionalism': 'الاحترافية',
      'quality': 'الجودة',
      'value_for_money': 'القيمة مقابل المال',
      'comment': 'تعليق',
      'submit': 'إرسال',
      'provider_dashboard': 'لوحة القيادة',
      'statistics': 'الإحصائيات',
      'total_revenue': 'إجمالي الإيرادات',
      'upcoming_bookings': 'الحجوزات القادمة',
      'required_field': 'هذا الحقل مطلوب',
      'invalid_phone': 'رقم هاتف غير صالح',
      'invalid_email': 'عنوان بريد إلكتروني غير صالح',
      'password_min_length': 'يجب أن تحتوي كلمة المرور على 8 أحرف على الأقل',
      'loading': 'جارٍ التحميل...',
      'error': 'خطأ',
      'success': 'نجاح',
      'retry': 'إعادة المحاولة',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  // Helper method for easy access
  String t(String key) => translate(key);
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'fr', 'ar'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
